import sys, os, io
fp = io.StringIO()
fp.write('''
#include <stdio.h>
''')

fnames = os.listdir(sys.argv[1]+'/include/capi')
for fname in fnames:
    if fname.split('.')[-1] == 'h':
        fp.write('#include "include/capi/%s"\n'%fname)

fp.write('''\
int main(){
    FILE *fp = fopen("gen\\\\libcefsizes.py", "wt");
    fprintf(fp, "\\
#\\n\\
# DO NOT MODIFY! THIS IS AUTOGENERATED FILE!\\n\\
#\\n\\
from .libcefstruct import *\\n\\
");
''')

fmt='fprintf(fp, "assert sizeof(%s)==%%zd\\n", sizeof(%s));\n'
for name in (
    'cef_accessibility_handler_t',
    'cef_app_t',
    'cef_audio_handler_t',
    'cef_auth_callback_t',
    'cef_browser_t',
    'cef_run_file_dialog_callback_t',
    'cef_navigation_entry_visitor_t',
    'cef_pdf_print_callback_t',
    'cef_download_image_callback_t',
    'cef_browser_host_t',
    'cef_browser_process_handler_t',
    'cef_callback_t',
    'cef_completion_callback_t',
    'cef_client_t',
    'cef_command_handler_t',
    'cef_command_line_t',
    'cef_run_context_menu_callback_t',
    'cef_context_menu_handler_t',
    'cef_context_menu_params_t',
    'cef_cookie_manager_t',
    'cef_cookie_visitor_t',
    'cef_set_cookie_callback_t',
    'cef_delete_cookies_callback_t',
    'cef_dev_tools_message_observer_t',
    'cef_file_dialog_callback_t',
    'cef_dialog_handler_t',
    'cef_display_handler_t',
    'cef_domvisitor_t',
    'cef_domdocument_t',
    'cef_domnode_t',
    'cef_before_download_callback_t',
    'cef_download_item_callback_t',
    'cef_download_handler_t',
    'cef_download_item_t',
    'cef_drag_data_t',
    'cef_drag_handler_t',
    'cef_extension_t',
    'cef_get_extension_resource_callback_t',
    'cef_extension_handler_t',
    'cef_find_handler_t',
    'cef_focus_handler_t',
    'cef_frame_t',
    'cef_frame_handler_t',
    'cef_image_t',
    'cef_jsdialog_callback_t',
    'cef_jsdialog_handler_t',
    'cef_keyboard_handler_t',
    'cef_life_span_handler_t',
    'cef_load_handler_t',
    'cef_media_router_t',
    'cef_media_observer_t',
    'cef_media_route_t',
    'cef_media_route_create_callback_t',
    'cef_media_sink_t',
    'cef_media_sink_device_info_callback_t',
    'cef_media_source_t',
    'cef_menu_model_t',
    'cef_menu_model_delegate_t',
    'cef_navigation_entry_t',
    'cef_print_dialog_callback_t',
    'cef_print_job_callback_t',
    'cef_print_handler_t',
    'cef_print_settings_t',
    'cef_process_message_t',
    'cef_registration_t',
    'cef_render_handler_t',
    'cef_render_process_handler_t',
    'cef_request_t',
    'cef_post_data_t',
    'cef_post_data_element_t',
    'cef_resolve_callback_t',
    'cef_request_context_t',
    'cef_request_context_handler_t',
    'cef_select_client_certificate_callback_t',
    'cef_request_handler_t',
    'cef_resource_bundle_t',
    'cef_resource_bundle_handler_t',
    'cef_resource_skip_callback_t',
    'cef_resource_read_callback_t',
    'cef_resource_handler_t',
    'cef_resource_request_handler_t',
    'cef_cookie_access_filter_t',
    'cef_response_t',
    'cef_response_filter_t',
    'cef_scheme_registrar_t',
    'cef_scheme_handler_factory_t',
    'cef_server_t',
    'cef_server_handler_t',
    'cef_sslinfo_t',
    'cef_sslstatus_t',
    'cef_read_handler_t',
    'cef_stream_reader_t',
    'cef_write_handler_t',
    'cef_stream_writer_t',
    'cef_string_visitor_t',
    'cef_task_t',
    'cef_task_runner_t',
    'cef_end_tracing_callback_t',
    'cef_urlrequest_t',
    'cef_urlrequest_client_t',
    'cef_v8context_t',
    'cef_v8handler_t',
    'cef_v8accessor_t',
    'cef_v8interceptor_t',
    'cef_v8exception_t',
    'cef_v8array_buffer_release_callback_t',
    'cef_v8value_t',
    'cef_v8stack_trace_t',
    'cef_v8stack_frame_t',
    'cef_value_t',
    'cef_binary_value_t',
    'cef_dictionary_value_t',
    'cef_list_value_t',
    'cef_x509cert_principal_t',
    'cef_x509certificate_t',
    'cef_xml_reader_t',
    'cef_zip_reader_t',
    'cef_touch_handle_state_t',
):
    fp.write(fmt%(name, name))

fp.write('''\
    fclose(fp);
}
''')

data = fp.getvalue()
open('sizes.c', 'wt').write(data)
