from . import enum


class CefPermissionRequestTypes(enum.IntEnum):
    CEF_PERMISSION_TYPE_NONE = 0
    CEF_PERMISSION_TYPE_ACCESSIBILITY_EVENTS = 1 << 0
    CEF_PERMISSION_TYPE_AR_SESSION = 1 << 1
    CEF_PERMISSION_TYPE_CAMERA_PAN_TILT_ZOOM = 1 << 2
    CEF_PERMISSION_TYPE_CAMERA_STREAM = 1 << 3
    CEF_PERMISSION_TYPE_CLIPBOARD = 1 << 4
    CEF_PERMISSION_TYPE_DISK_QUOTA = 1 << 5
    CEF_PERMISSION_TYPE_LOCAL_FONTS = 1 << 6
    CEF_PERMISSION_TYPE_GEOLOCATION = 1 << 7
    CEF_PERMISSION_TYPE_IDLE_DETECTION = 1 << 8
    CEF_PERMISSION_TYPE_MIC_STREAM = 1 << 9
    CEF_PERMISSION_TYPE_MIDI_SYSEX = 1 << 10
    CEF_PERMISSION_TYPE_MULTIPLE_DOWNLOADS = 1 << 11
    CEF_PERMISSION_TYPE_NOTIFICATIONS = 1 << 12
    CEF_PERMISSION_TYPE_PROTECTED_MEDIA_IDENTIFIER = 1 << 13
    CEF_PERMISSION_TYPE_REGISTER_PROTOCOL_HANDLER = 1 << 14
    CEF_PERMISSION_TYPE_SECURITY_ATTESTATION = 1 << 15
    CEF_PERMISSION_TYPE_STORAGE_ACCESS = 1 << 16
    CEF_PERMISSION_TYPE_U2F_API_REQUEST = 1 << 17
    CEF_PERMISSION_TYPE_VR_SESSION = 1 << 18
    CEF_PERMISSION_TYPE_WINDOW_PLACEMENT = 1 << 19
