#
# DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
#
from .libcefdef import *
from cefct.cef_string_t import *
from cefct.libcefinternal_t import *

#
# https://v4.chriskrycho.com/2015/ctypes-structures-and-dll-exports.html
#
import enum
class IntEnum(enum.IntEnum):
    """A ctypes-compatible IntEnum superclass."""

    def __init__(self, value):
        self._as_parameter = int(value)

    @classmethod
    def from_param(cls, obj):
        return int(obj)

if 1:


#class cef_log_severity_t(enum):
    LOGSEVERITY_DEFAULT = 1
    LOGSEVERITY_VERBOSE = 2
    LOGSEVERITY_DEBUG = 2
    LOGSEVERITY_INFO = 3
    LOGSEVERITY_WARNING = 4
    LOGSEVERITY_ERROR = 5
    LOGSEVERITY_FATAL = 6
    LOGSEVERITY_DISABLE = 99


#class cef_state_t(enum):
    STATE_DEFAULT = 0
    STATE_ENABLED = 1
    STATE_DISABLED = 2


#class cef_return_value_t(enum):
    RV_CANCEL = 0
    RV_CONTINUE = 1
    RV_CONTINUE_ASYNC = 2


#class cef_cookie_priority_t(enum):
    CEF_COOKIE_PRIORITY_LOW = -1
    CEF_COOKIE_PRIORITY_MEDIUM = 0
    CEF_COOKIE_PRIORITY_HIGH = 1


#class cef_cookie_same_site_t(enum):
    CEF_COOKIE_SAME_SITE_UNSPECIFIED = 1
    CEF_COOKIE_SAME_SITE_NO_RESTRICTION = 2
    CEF_COOKIE_SAME_SITE_LAX_MODE = 3
    CEF_COOKIE_SAME_SITE_STRICT_MODE = 4


#class cef_termination_status_t(enum):
    TS_ABNORMAL_TERMINATION = 1
    TS_PROCESS_WAS_KILLED = 2
    TS_PROCESS_CRASHED = 3
    TS_PROCESS_OOM = 4


#class cef_path_key_t(enum):
    PK_DIR_CURRENT = 1
    PK_DIR_EXE = 2
    PK_DIR_MODULE = 3
    PK_DIR_TEMP = 4
    PK_FILE_EXE = 5
    PK_FILE_MODULE = 6
    PK_LOCAL_APP_DATA = 7
    PK_USER_DATA = 8
    PK_DIR_RESOURCES = 9


#class cef_storage_type_t(enum):
    ST_LOCALSTORAGE = 0
    ST_SESSIONSTORAGE = 1


#class cef_errorcode_t(enum):
    ERR_NONE = 0


#class cef_cert_status_t(enum):
    CERT_STATUS_NONE = 0
    CERT_STATUS_COMMON_NAME_INVALID = 1
    CERT_STATUS_DATE_INVALID = 2
    CERT_STATUS_AUTHORITY_INVALID = 4
    CERT_STATUS_NO_REVOCATION_MECHANISM = 16
    CERT_STATUS_UNABLE_TO_CHECK_REVOCATION = 32
    CERT_STATUS_REVOKED = 64
    CERT_STATUS_INVALID = 128
    CERT_STATUS_WEAK_SIGNATURE_ALGORITHM = 256
    CERT_STATUS_NON_UNIQUE_NAME = 1024
    CERT_STATUS_WEAK_KEY = 2048
    CERT_STATUS_PINNED_KEY_MISSING = 8192
    CERT_STATUS_NAME_CONSTRAINT_VIOLATION = 16384
    CERT_STATUS_VALIDITY_TOO_LONG = 32768
    CERT_STATUS_IS_EV = 65536
    CERT_STATUS_REV_CHECKING_ENABLED = 131072
    CERT_STATUS_SHA1_SIGNATURE_PRESENT = 524288
    CERT_STATUS_CT_COMPLIANCE_FAILED = 1048576


#class cef_window_open_disposition_t(enum):
    WOD_UNKNOWN = 1
    WOD_CURRENT_TAB = 2
    WOD_SINGLETON_TAB = 3
    WOD_NEW_FOREGROUND_TAB = 4
    WOD_NEW_BACKGROUND_TAB = 5
    WOD_NEW_POPUP = 6
    WOD_NEW_WINDOW = 7
    WOD_SAVE_TO_DISK = 8
    WOD_OFF_THE_RECORD = 9
    WOD_IGNORE_ACTION = 10
    WOD_SWITCH_TO_TAB = 11
    WOD_NEW_PICTURE_IN_PICTURE = 12


#class cef_drag_operations_mask_t(enum):
    DRAG_OPERATION_NONE = 0
    DRAG_OPERATION_COPY = 1
    DRAG_OPERATION_LINK = 2
    DRAG_OPERATION_GENERIC = 4
    DRAG_OPERATION_PRIVATE = 8
    DRAG_OPERATION_MOVE = 16
    DRAG_OPERATION_DELETE = 32
    DRAG_OPERATION_EVERY = 4294967295


#class cef_text_input_mode_t(enum):
    CEF_TEXT_INPUT_MODE_DEFAULT = 1
    CEF_TEXT_INPUT_MODE_NONE = 2
    CEF_TEXT_INPUT_MODE_TEXT = 3
    CEF_TEXT_INPUT_MODE_TEL = 4
    CEF_TEXT_INPUT_MODE_URL = 5
    CEF_TEXT_INPUT_MODE_EMAIL = 6
    CEF_TEXT_INPUT_MODE_NUMERIC = 7
    CEF_TEXT_INPUT_MODE_DECIMAL = 8
    CEF_TEXT_INPUT_MODE_SEARCH = 9
    CEF_TEXT_INPUT_MODE_MAX = 9


#class cef_v8_accesscontrol_t(enum):
    V8_ACCESS_CONTROL_DEFAULT = 0
    V8_ACCESS_CONTROL_ALL_CAN_READ = 1
    V8_ACCESS_CONTROL_ALL_CAN_WRITE = 2
    V8_ACCESS_CONTROL_PROHIBITS_OVERWRITING = 4


#class cef_v8_propertyattribute_t(enum):
    V8_PROPERTY_ATTRIBUTE_NONE = 0
    V8_PROPERTY_ATTRIBUTE_READONLY = 1
    V8_PROPERTY_ATTRIBUTE_DONTENUM = 2
    V8_PROPERTY_ATTRIBUTE_DONTDELETE = 4


#class cef_postdataelement_type_t(enum):
    PDE_TYPE_EMPTY = 0
    PDE_TYPE_BYTES = 1
    PDE_TYPE_FILE = 2


#class cef_resource_type_t(enum):
    RT_MAIN_FRAME = 0
    RT_SUB_FRAME = 1
    RT_STYLESHEET = 2
    RT_SCRIPT = 3
    RT_IMAGE = 4
    RT_FONT_RESOURCE = 5
    RT_SUB_RESOURCE = 6
    RT_OBJECT = 7
    RT_MEDIA = 8
    RT_WORKER = 9
    RT_SHARED_WORKER = 10
    RT_PREFETCH = 11
    RT_FAVICON = 12
    RT_XHR = 13
    RT_PING = 14
    RT_SERVICE_WORKER = 15
    RT_CSP_REPORT = 16
    RT_PLUGIN_RESOURCE = 17
    RT_NAVIGATION_PRELOAD_MAIN_FRAME = 19
    RT_NAVIGATION_PRELOAD_SUB_FRAME = 20


#class cef_transition_type_t(enum):
    TT_LINK = 0
    TT_EXPLICIT = 1
    TT_AUTO_BOOKMARK = 2
    TT_AUTO_SUBFRAME = 3
    TT_MANUAL_SUBFRAME = 4
    TT_GENERATED = 5
    TT_AUTO_TOPLEVEL = 6
    TT_FORM_SUBMIT = 7
    TT_RELOAD = 8
    TT_KEYWORD = 9
    TT_KEYWORD_GENERATED = 10
    TT_SOURCE_MASK = 255
    TT_BLOCKED_FLAG = 8388608
    TT_FORWARD_BACK_FLAG = 16777216
    TT_DIRECT_LOAD_FLAG = 33554432
    TT_HOME_PAGE_FLAG = 67108864
    TT_FROM_API_FLAG = 134217728
    TT_CHAIN_START_FLAG = 268435456
    TT_CHAIN_END_FLAG = 536870912
    TT_CLIENT_REDIRECT_FLAG = 1073741824
    TT_SERVER_REDIRECT_FLAG = 2147483648
    TT_IS_REDIRECT_MASK = 3221225472
    TT_QUALIFIER_MASK = 4294967040


#class cef_urlrequest_flags_t(enum):
    UR_FLAG_NONE = 0
    UR_FLAG_SKIP_CACHE = 1
    UR_FLAG_ONLY_FROM_CACHE = 2
    UR_FLAG_DISABLE_CACHE = 4
    UR_FLAG_ALLOW_STORED_CREDENTIALS = 8
    UR_FLAG_REPORT_UPLOAD_PROGRESS = 16
    UR_FLAG_NO_DOWNLOAD_DATA = 32
    UR_FLAG_NO_RETRY_ON_5XX = 64
    UR_FLAG_STOP_ON_REDIRECT = 128


#class cef_urlrequest_status_t(enum):
    UR_UNKNOWN = 0
    UR_SUCCESS = 1
    UR_IO_PENDING = 2
    UR_CANCELED = 3
    UR_FAILED = 4


#class cef_process_id_t(enum):
    PID_BROWSER = 1
    PID_RENDERER = 2


#class cef_thread_id_t(enum):
    TID_UI = 1
    TID_FILE_BACKGROUND = 2
    TID_FILE_USER_VISIBLE = 3
    TID_FILE_USER_BLOCKING = 4
    TID_PROCESS_LAUNCHER = 5
    TID_IO = 6
    TID_RENDERER = 7


#class cef_thread_priority_t(enum):
    TP_BACKGROUND = 1
    TP_NORMAL = 2
    TP_DISPLAY = 3
    TP_REALTIME_AUDIO = 4


#class cef_message_loop_type_t(enum):
    ML_TYPE_DEFAULT = 1
    ML_TYPE_UI = 2
    ML_TYPE_IO = 3


#class cef_com_init_mode_t(enum):
    COM_INIT_MODE_NONE = 1
    COM_INIT_MODE_STA = 2
    COM_INIT_MODE_MTA = 3


#class cef_value_type_t(enum):
    VTYPE_INVALID = 0
    VTYPE_NULL = 1
    VTYPE_BOOL = 2
    VTYPE_INT = 3
    VTYPE_DOUBLE = 4
    VTYPE_STRING = 5
    VTYPE_BINARY = 6
    VTYPE_DICTIONARY = 7
    VTYPE_LIST = 8


#class cef_jsdialog_type_t(enum):
    JSDIALOGTYPE_ALERT = 0
    JSDIALOGTYPE_CONFIRM = 1
    JSDIALOGTYPE_PROMPT = 2


#class cef_menu_id_t(enum):
    MENU_ID_BACK = 100
    MENU_ID_FORWARD = 101
    MENU_ID_RELOAD = 102
    MENU_ID_RELOAD_NOCACHE = 103
    MENU_ID_STOPLOAD = 104
    MENU_ID_UNDO = 110
    MENU_ID_REDO = 111
    MENU_ID_CUT = 112
    MENU_ID_COPY = 113
    MENU_ID_PASTE = 114
    MENU_ID_DELETE = 115
    MENU_ID_SELECT_ALL = 116
    MENU_ID_FIND = 130
    MENU_ID_PRINT = 131
    MENU_ID_VIEW_SOURCE = 132
    MENU_ID_SPELLCHECK_SUGGESTION_0 = 200
    MENU_ID_SPELLCHECK_SUGGESTION_1 = 201
    MENU_ID_SPELLCHECK_SUGGESTION_2 = 202
    MENU_ID_SPELLCHECK_SUGGESTION_3 = 203
    MENU_ID_SPELLCHECK_SUGGESTION_4 = 204
    MENU_ID_SPELLCHECK_SUGGESTION_LAST = 204
    MENU_ID_NO_SPELLING_SUGGESTIONS = 205
    MENU_ID_ADD_TO_DICTIONARY = 206
    MENU_ID_CUSTOM_FIRST = 220
    MENU_ID_CUSTOM_LAST = 250
    MENU_ID_USER_FIRST = 26500
    MENU_ID_USER_LAST = 28500


#class cef_mouse_button_type_t(enum):
    MBT_LEFT = 0
    MBT_MIDDLE = 1
    MBT_RIGHT = 2


#class cef_touch_event_type_t(enum):
    CEF_TET_RELEASED = 0
    CEF_TET_PRESSED = 1
    CEF_TET_MOVED = 2
    CEF_TET_CANCELLED = 3


#class cef_pointer_type_t(enum):
    CEF_POINTER_TYPE_TOUCH = 0
    CEF_POINTER_TYPE_MOUSE = 1
    CEF_POINTER_TYPE_PEN = 2
    CEF_POINTER_TYPE_ERASER = 3
    CEF_POINTER_TYPE_UNKNOWN = 4


#class cef_paint_element_type_t(enum):
    PET_VIEW = 0
    PET_POPUP = 1


#class cef_event_flags_t(enum):
    EVENTFLAG_NONE = 0
    EVENTFLAG_CAPS_LOCK_ON = 1
    EVENTFLAG_SHIFT_DOWN = 2
    EVENTFLAG_CONTROL_DOWN = 4
    EVENTFLAG_ALT_DOWN = 8
    EVENTFLAG_LEFT_MOUSE_BUTTON = 16
    EVENTFLAG_MIDDLE_MOUSE_BUTTON = 32
    EVENTFLAG_RIGHT_MOUSE_BUTTON = 64
    EVENTFLAG_COMMAND_DOWN = 128
    EVENTFLAG_NUM_LOCK_ON = 256
    EVENTFLAG_IS_KEY_PAD = 512
    EVENTFLAG_IS_LEFT = 1024
    EVENTFLAG_IS_RIGHT = 2048
    EVENTFLAG_ALTGR_DOWN = 4096
    EVENTFLAG_IS_REPEAT = 8192


#class cef_menu_item_type_t(enum):
    MENUITEMTYPE_NONE = 1
    MENUITEMTYPE_COMMAND = 2
    MENUITEMTYPE_CHECK = 3
    MENUITEMTYPE_RADIO = 4
    MENUITEMTYPE_SEPARATOR = 5
    MENUITEMTYPE_SUBMENU = 6


#class cef_context_menu_type_flags_t(enum):
    CM_TYPEFLAG_NONE = 0
    CM_TYPEFLAG_PAGE = 1
    CM_TYPEFLAG_FRAME = 2
    CM_TYPEFLAG_LINK = 4
    CM_TYPEFLAG_MEDIA = 8
    CM_TYPEFLAG_SELECTION = 16
    CM_TYPEFLAG_EDITABLE = 32


#class cef_context_menu_media_type_t(enum):
    CM_MEDIATYPE_NONE = 1
    CM_MEDIATYPE_IMAGE = 2
    CM_MEDIATYPE_VIDEO = 3
    CM_MEDIATYPE_AUDIO = 4
    CM_MEDIATYPE_CANVAS = 5
    CM_MEDIATYPE_FILE = 6
    CM_MEDIATYPE_PLUGIN = 7


#class cef_context_menu_media_state_flags_t(enum):
    CM_MEDIAFLAG_NONE = 0
    CM_MEDIAFLAG_IN_ERROR = 1
    CM_MEDIAFLAG_PAUSED = 2
    CM_MEDIAFLAG_MUTED = 4
    CM_MEDIAFLAG_LOOP = 8
    CM_MEDIAFLAG_CAN_SAVE = 16
    CM_MEDIAFLAG_HAS_AUDIO = 32
    CM_MEDIAFLAG_CAN_TOGGLE_CONTROLS = 64
    CM_MEDIAFLAG_CONTROLS = 128
    CM_MEDIAFLAG_CAN_PRINT = 256
    CM_MEDIAFLAG_CAN_ROTATE = 512
    CM_MEDIAFLAG_CAN_PICTURE_IN_PICTURE = 1024
    CM_MEDIAFLAG_PICTURE_IN_PICTURE = 2048
    CM_MEDIAFLAG_CAN_LOOP = 4096


#class cef_context_menu_edit_state_flags_t(enum):
    CM_EDITFLAG_NONE = 0
    CM_EDITFLAG_CAN_UNDO = 1
    CM_EDITFLAG_CAN_REDO = 2
    CM_EDITFLAG_CAN_CUT = 4
    CM_EDITFLAG_CAN_COPY = 8
    CM_EDITFLAG_CAN_PASTE = 16
    CM_EDITFLAG_CAN_DELETE = 32
    CM_EDITFLAG_CAN_SELECT_ALL = 64
    CM_EDITFLAG_CAN_TRANSLATE = 128
    CM_EDITFLAG_CAN_EDIT_RICHLY = 256


#class cef_quick_menu_edit_state_flags_t(enum):
    QM_EDITFLAG_NONE = 0
    QM_EDITFLAG_CAN_ELLIPSIS = 1
    QM_EDITFLAG_CAN_CUT = 2
    QM_EDITFLAG_CAN_COPY = 4
    QM_EDITFLAG_CAN_PASTE = 8


#class cef_key_event_type_t(enum):
    KEYEVENT_RAWKEYDOWN = 0
    KEYEVENT_KEYDOWN = 1
    KEYEVENT_KEYUP = 2
    KEYEVENT_CHAR = 3


#class cef_focus_source_t(enum):
    FOCUS_SOURCE_NAVIGATION = 0
    FOCUS_SOURCE_SYSTEM = 1


#class cef_navigation_type_t(enum):
    NAVIGATION_LINK_CLICKED = 0
    NAVIGATION_FORM_SUBMITTED = 1
    NAVIGATION_BACK_FORWARD = 2
    NAVIGATION_RELOAD = 3
    NAVIGATION_FORM_RESUBMITTED = 4
    NAVIGATION_OTHER = 5


#class cef_xml_encoding_type_t(enum):
    XML_ENCODING_NONE = 0
    XML_ENCODING_UTF8 = 1
    XML_ENCODING_UTF16LE = 2
    XML_ENCODING_UTF16BE = 3
    XML_ENCODING_ASCII = 4


#class cef_xml_node_type_t(enum):
    XML_NODE_UNSUPPORTED = 0
    XML_NODE_PROCESSING_INSTRUCTION = 1
    XML_NODE_DOCUMENT_TYPE = 2
    XML_NODE_ELEMENT_START = 3
    XML_NODE_ELEMENT_END = 4
    XML_NODE_ATTRIBUTE = 5
    XML_NODE_TEXT = 6
    XML_NODE_CDATA = 7
    XML_NODE_ENTITY_REFERENCE = 8
    XML_NODE_WHITESPACE = 9
    XML_NODE_COMMENT = 10


#class cef_dom_document_type_t(enum):
    DOM_DOCUMENT_TYPE_UNKNOWN = 0
    DOM_DOCUMENT_TYPE_HTML = 1
    DOM_DOCUMENT_TYPE_XHTML = 2
    DOM_DOCUMENT_TYPE_PLUGIN = 3


#class cef_dom_event_category_t(enum):
    DOM_EVENT_CATEGORY_UNKNOWN = 0
    DOM_EVENT_CATEGORY_UI = 1
    DOM_EVENT_CATEGORY_MOUSE = 2
    DOM_EVENT_CATEGORY_MUTATION = 4
    DOM_EVENT_CATEGORY_KEYBOARD = 8
    DOM_EVENT_CATEGORY_TEXT = 16
    DOM_EVENT_CATEGORY_COMPOSITION = 32
    DOM_EVENT_CATEGORY_DRAG = 64
    DOM_EVENT_CATEGORY_CLIPBOARD = 128
    DOM_EVENT_CATEGORY_MESSAGE = 256
    DOM_EVENT_CATEGORY_WHEEL = 512
    DOM_EVENT_CATEGORY_BEFORE_TEXT_INSERTED = 1024
    DOM_EVENT_CATEGORY_OVERFLOW = 2048
    DOM_EVENT_CATEGORY_PAGE_TRANSITION = 4096
    DOM_EVENT_CATEGORY_POPSTATE = 8192
    DOM_EVENT_CATEGORY_PROGRESS = 16384
    DOM_EVENT_CATEGORY_XMLHTTPREQUEST_PROGRESS = 32768


#class cef_dom_event_phase_t(enum):
    DOM_EVENT_PHASE_UNKNOWN = 0
    DOM_EVENT_PHASE_CAPTURING = 1
    DOM_EVENT_PHASE_AT_TARGET = 2
    DOM_EVENT_PHASE_BUBBLING = 3


#class cef_dom_node_type_t(enum):
    DOM_NODE_TYPE_UNSUPPORTED = 0
    DOM_NODE_TYPE_ELEMENT = 1
    DOM_NODE_TYPE_ATTRIBUTE = 2
    DOM_NODE_TYPE_TEXT = 3
    DOM_NODE_TYPE_CDATA_SECTION = 4
    DOM_NODE_TYPE_PROCESSING_INSTRUCTIONS = 5
    DOM_NODE_TYPE_COMMENT = 6
    DOM_NODE_TYPE_DOCUMENT = 7
    DOM_NODE_TYPE_DOCUMENT_TYPE = 8
    DOM_NODE_TYPE_DOCUMENT_FRAGMENT = 9


#class cef_file_dialog_mode_t(enum):
    FILE_DIALOG_OPEN = 0
    FILE_DIALOG_OPEN_MULTIPLE = 1
    FILE_DIALOG_OPEN_FOLDER = 2
    FILE_DIALOG_SAVE = 3


#class cef_color_model_t(enum):
    COLOR_MODEL_UNKNOWN = 1
    COLOR_MODEL_GRAY = 2
    COLOR_MODEL_COLOR = 3
    COLOR_MODEL_CMYK = 4
    COLOR_MODEL_CMY = 5
    COLOR_MODEL_KCMY = 6
    COLOR_MODEL_CMY_K = 7
    COLOR_MODEL_BLACK = 8
    COLOR_MODEL_GRAYSCALE = 9
    COLOR_MODEL_RGB = 10
    COLOR_MODEL_RGB16 = 11
    COLOR_MODEL_RGBA = 12
    COLOR_MODEL_COLORMODE_COLOR = 13
    COLOR_MODEL_COLORMODE_MONOCHROME = 14
    COLOR_MODEL_HP_COLOR_COLOR = 15
    COLOR_MODEL_HP_COLOR_BLACK = 16
    COLOR_MODEL_PRINTOUTMODE_NORMAL = 17
    COLOR_MODEL_PRINTOUTMODE_NORMAL_GRAY = 18
    COLOR_MODEL_PROCESSCOLORMODEL_CMYK = 19
    COLOR_MODEL_PROCESSCOLORMODEL_GREYSCALE = 20
    COLOR_MODEL_PROCESSCOLORMODEL_RGB = 21


#class cef_duplex_mode_t(enum):
    DUPLEX_MODE_UNKNOWN = -1
    DUPLEX_MODE_SIMPLEX = 0
    DUPLEX_MODE_LONG_EDGE = 1
    DUPLEX_MODE_SHORT_EDGE = 2


#class cef_cursor_type_t(enum):
    CT_POINTER = 0
    CT_CROSS = 1
    CT_HAND = 2
    CT_IBEAM = 3
    CT_WAIT = 4
    CT_HELP = 5
    CT_EASTRESIZE = 6
    CT_NORTHRESIZE = 7
    CT_NORTHEASTRESIZE = 8
    CT_NORTHWESTRESIZE = 9
    CT_SOUTHRESIZE = 10
    CT_SOUTHEASTRESIZE = 11
    CT_SOUTHWESTRESIZE = 12
    CT_WESTRESIZE = 13
    CT_NORTHSOUTHRESIZE = 14
    CT_EASTWESTRESIZE = 15
    CT_NORTHEASTSOUTHWESTRESIZE = 16
    CT_NORTHWESTSOUTHEASTRESIZE = 17
    CT_COLUMNRESIZE = 18
    CT_ROWRESIZE = 19
    CT_MIDDLEPANNING = 20
    CT_EASTPANNING = 21
    CT_NORTHPANNING = 22
    CT_NORTHEASTPANNING = 23
    CT_NORTHWESTPANNING = 24
    CT_SOUTHPANNING = 25
    CT_SOUTHEASTPANNING = 26
    CT_SOUTHWESTPANNING = 27
    CT_WESTPANNING = 28
    CT_MOVE = 29
    CT_VERTICALTEXT = 30
    CT_CELL = 31
    CT_CONTEXTMENU = 32
    CT_ALIAS = 33
    CT_PROGRESS = 34
    CT_NODROP = 35
    CT_COPY = 36
    CT_NONE = 37
    CT_NOTALLOWED = 38
    CT_ZOOMIN = 39
    CT_ZOOMOUT = 40
    CT_GRAB = 41
    CT_GRABBING = 42
    CT_MIDDLE_PANNING_VERTICAL = 43
    CT_MIDDLE_PANNING_HORIZONTAL = 44
    CT_CUSTOM = 45
    CT_DND_NONE = 46
    CT_DND_MOVE = 47
    CT_DND_COPY = 48
    CT_DND_LINK = 49


#class cef_uri_unescape_rule_t(enum):
    UU_NONE = 0
    UU_NORMAL = 1
    UU_SPACES = 2
    UU_PATH_SEPARATORS = 4
    UU_URL_SPECIAL_CHARS_EXCEPT_PATH_SEPARATORS = 8
    UU_REPLACE_PLUS_WITH_SPACE = 16


#class cef_json_parser_options_t(enum):
    JSON_PARSER_RFC = 0
    JSON_PARSER_ALLOW_TRAILING_COMMAS = 1


#class cef_json_writer_options_t(enum):
    JSON_WRITER_DEFAULT = 0
    JSON_WRITER_OMIT_BINARY_VALUES = 1
    JSON_WRITER_OMIT_DOUBLE_TYPE_PRESERVATION = 2
    JSON_WRITER_PRETTY_PRINT = 4


#class cef_pdf_print_margin_type_t(enum):
    PDF_PRINT_MARGIN_DEFAULT = 1
    PDF_PRINT_MARGIN_NONE = 2
    PDF_PRINT_MARGIN_MINIMUM = 3
    PDF_PRINT_MARGIN_CUSTOM = 4


#class cef_scale_factor_t(enum):
    SCALE_FACTOR_NONE = 0
    SCALE_FACTOR_100P = 1
    SCALE_FACTOR_125P = 2
    SCALE_FACTOR_133P = 3
    SCALE_FACTOR_140P = 4
    SCALE_FACTOR_150P = 5
    SCALE_FACTOR_180P = 6
    SCALE_FACTOR_200P = 7
    SCALE_FACTOR_250P = 8
    SCALE_FACTOR_300P = 9


#class cef_referrer_policy_t(enum):
    REFERRER_POLICY_CLEAR_REFERRER_ON_TRANSITION_FROM_SECURE_TO_INSECURE = 1
    REFERRER_POLICY_DEFAULT = 1
    REFERRER_POLICY_REDUCE_REFERRER_GRANULARITY_ON_TRANSITION_CROSS_ORIGIN = 2
    REFERRER_POLICY_ORIGIN_ONLY_ON_TRANSITION_CROSS_ORIGIN = 3
    REFERRER_POLICY_NEVER_CLEAR_REFERRER = 4
    REFERRER_POLICY_ORIGIN = 5
    REFERRER_POLICY_CLEAR_REFERRER_ON_TRANSITION_CROSS_ORIGIN = 6
    REFERRER_POLICY_ORIGIN_CLEAR_ON_TRANSITION_FROM_SECURE_TO_INSECURE = 7
    REFERRER_POLICY_NO_REFERRER = 8
    REFERRER_POLICY_LAST_VALUE = 8


#class cef_response_filter_status_t(enum):
    RESPONSE_FILTER_NEED_MORE_DATA = 1
    RESPONSE_FILTER_DONE = 2
    RESPONSE_FILTER_ERROR = 3


#class cef_color_type_t(enum):
    CEF_COLOR_TYPE_RGBA_8888 = 1
    CEF_COLOR_TYPE_BGRA_8888 = 2


#class cef_alpha_type_t(enum):
    CEF_ALPHA_TYPE_OPAQUE = 1
    CEF_ALPHA_TYPE_PREMULTIPLIED = 2
    CEF_ALPHA_TYPE_POSTMULTIPLIED = 3


#class cef_text_style_t(enum):
    CEF_TEXT_STYLE_BOLD = 1
    CEF_TEXT_STYLE_ITALIC = 2
    CEF_TEXT_STYLE_STRIKE = 3
    CEF_TEXT_STYLE_DIAGONAL_STRIKE = 4
    CEF_TEXT_STYLE_UNDERLINE = 5


#class cef_main_axis_alignment_t(enum):
    CEF_MAIN_AXIS_ALIGNMENT_START = 1
    CEF_MAIN_AXIS_ALIGNMENT_CENTER = 2
    CEF_MAIN_AXIS_ALIGNMENT_END = 3


#class cef_cross_axis_alignment_t(enum):
    CEF_CROSS_AXIS_ALIGNMENT_STRETCH = 1
    CEF_CROSS_AXIS_ALIGNMENT_START = 2
    CEF_CROSS_AXIS_ALIGNMENT_CENTER = 3
    CEF_CROSS_AXIS_ALIGNMENT_END = 4


#class cef_button_state_t(enum):
    CEF_BUTTON_STATE_NORMAL = 1
    CEF_BUTTON_STATE_HOVERED = 2
    CEF_BUTTON_STATE_PRESSED = 3
    CEF_BUTTON_STATE_DISABLED = 4


#class cef_horizontal_alignment_t(enum):
    CEF_HORIZONTAL_ALIGNMENT_LEFT = 1
    CEF_HORIZONTAL_ALIGNMENT_CENTER = 2
    CEF_HORIZONTAL_ALIGNMENT_RIGHT = 3


#class cef_menu_anchor_position_t(enum):
    CEF_MENU_ANCHOR_TOPLEFT = 1
    CEF_MENU_ANCHOR_TOPRIGHT = 2
    CEF_MENU_ANCHOR_BOTTOMCENTER = 3


#class cef_menu_color_type_t(enum):
    CEF_MENU_COLOR_TEXT = 1
    CEF_MENU_COLOR_TEXT_HOVERED = 2
    CEF_MENU_COLOR_TEXT_ACCELERATOR = 3
    CEF_MENU_COLOR_TEXT_ACCELERATOR_HOVERED = 4
    CEF_MENU_COLOR_BACKGROUND = 5
    CEF_MENU_COLOR_BACKGROUND_HOVERED = 6
    CEF_MENU_COLOR_COUNT = 7


#class cef_ssl_version_t(enum):
    SSL_CONNECTION_VERSION_UNKNOWN = 0
    SSL_CONNECTION_VERSION_SSL2 = 1
    SSL_CONNECTION_VERSION_SSL3 = 2
    SSL_CONNECTION_VERSION_TLS1 = 3
    SSL_CONNECTION_VERSION_TLS1_1 = 4
    SSL_CONNECTION_VERSION_TLS1_2 = 5
    SSL_CONNECTION_VERSION_TLS1_3 = 6
    SSL_CONNECTION_VERSION_QUIC = 7


#class cef_ssl_content_status_t(enum):
    SSL_CONTENT_NORMAL_CONTENT = 0
    SSL_CONTENT_DISPLAYED_INSECURE_CONTENT = 1
    SSL_CONTENT_RAN_INSECURE_CONTENT = 2


#class cef_scheme_options_t(enum):
    CEF_SCHEME_OPTION_NONE = 0
    CEF_SCHEME_OPTION_STANDARD = 1
    CEF_SCHEME_OPTION_LOCAL = 2
    CEF_SCHEME_OPTION_DISPLAY_ISOLATED = 4
    CEF_SCHEME_OPTION_SECURE = 8
    CEF_SCHEME_OPTION_CORS_ENABLED = 16
    CEF_SCHEME_OPTION_CSP_BYPASSING = 32
    CEF_SCHEME_OPTION_FETCH_ENABLED = 64


#class cef_composition_underline_style_t(enum):
    CEF_CUS_SOLID = 1
    CEF_CUS_DOT = 2
    CEF_CUS_DASH = 3
    CEF_CUS_NONE = 4


#class cef_channel_layout_t(enum):
    CEF_CHANNEL_LAYOUT_NONE = 0
    CEF_CHANNEL_LAYOUT_UNSUPPORTED = 1
    CEF_CHANNEL_LAYOUT_MONO = 2
    CEF_CHANNEL_LAYOUT_STEREO = 3
    CEF_CHANNEL_LAYOUT_2_1 = 4
    CEF_CHANNEL_LAYOUT_SURROUND = 5
    CEF_CHANNEL_LAYOUT_4_0 = 6
    CEF_CHANNEL_LAYOUT_2_2 = 7
    CEF_CHANNEL_LAYOUT_QUAD = 8
    CEF_CHANNEL_LAYOUT_5_0 = 9
    CEF_CHANNEL_LAYOUT_5_1 = 10
    CEF_CHANNEL_LAYOUT_5_0_BACK = 11
    CEF_CHANNEL_LAYOUT_5_1_BACK = 12
    CEF_CHANNEL_LAYOUT_7_0 = 13
    CEF_CHANNEL_LAYOUT_7_1 = 14
    CEF_CHANNEL_LAYOUT_7_1_WIDE = 15
    CEF_CHANNEL_LAYOUT_STEREO_DOWNMIX = 16
    CEF_CHANNEL_LAYOUT_2POINT1 = 17
    CEF_CHANNEL_LAYOUT_3_1 = 18
    CEF_CHANNEL_LAYOUT_4_1 = 19
    CEF_CHANNEL_LAYOUT_6_0 = 20
    CEF_CHANNEL_LAYOUT_6_0_FRONT = 21
    CEF_CHANNEL_LAYOUT_HEXAGONAL = 22
    CEF_CHANNEL_LAYOUT_6_1 = 23
    CEF_CHANNEL_LAYOUT_6_1_BACK = 24
    CEF_CHANNEL_LAYOUT_6_1_FRONT = 25
    CEF_CHANNEL_LAYOUT_7_0_FRONT = 26
    CEF_CHANNEL_LAYOUT_7_1_WIDE_BACK = 27
    CEF_CHANNEL_LAYOUT_OCTAGONAL = 28
    CEF_CHANNEL_LAYOUT_DISCRETE = 29
    CEF_CHANNEL_LAYOUT_STEREO_AND_KEYBOARD_MIC = 30
    CEF_CHANNEL_LAYOUT_4_1_QUAD_SIDE = 31
    CEF_CHANNEL_LAYOUT_BITSTREAM = 32
    CEF_CHANNEL_LAYOUT_5_1_4_DOWNMIX = 33
    CEF_CHANNEL_LAYOUT_MAX = 33


#class cef_media_route_create_result_t(enum):
    CEF_MRCR_UNKNOWN_ERROR = 0
    CEF_MRCR_OK = 1
    CEF_MRCR_TIMED_OUT = 2
    CEF_MRCR_ROUTE_NOT_FOUND = 3
    CEF_MRCR_SINK_NOT_FOUND = 4
    CEF_MRCR_INVALID_ORIGIN = 5
    CEF_MRCR_NO_SUPPORTED_PROVIDER = 7
    CEF_MRCR_CANCELLED = 8
    CEF_MRCR_ROUTE_ALREADY_EXISTS = 9
    CEF_MRCR_ROUTE_ALREADY_TERMINATED = 11


#class cef_media_route_connection_state_t(enum):
    CEF_MRCS_UNKNOWN = 1
    CEF_MRCS_CONNECTING = 2
    CEF_MRCS_CONNECTED = 3
    CEF_MRCS_CLOSED = 4
    CEF_MRCS_TERMINATED = 5


#class cef_media_sink_icon_type_t(enum):
    CEF_MSIT_CAST = 1
    CEF_MSIT_CAST_AUDIO_GROUP = 2
    CEF_MSIT_CAST_AUDIO = 3
    CEF_MSIT_MEETING = 4
    CEF_MSIT_HANGOUT = 5
    CEF_MSIT_EDUCATION = 6
    CEF_MSIT_WIRED_DISPLAY = 7
    CEF_MSIT_GENERIC = 8
    CEF_MSIT_TOTAL_COUNT = 9


#class cef_text_field_commands_t(enum):
    CEF_TFC_CUT = 1
    CEF_TFC_COPY = 2
    CEF_TFC_PASTE = 3
    CEF_TFC_UNDO = 4
    CEF_TFC_DELETE = 5
    CEF_TFC_SELECT_ALL = 6


#class cef_chrome_toolbar_type_t(enum):
    CEF_CTT_NONE = 1
    CEF_CTT_NORMAL = 2
    CEF_CTT_LOCATION = 3


#class cef_docking_mode_t(enum):
    CEF_DOCKING_MODE_TOP_LEFT = 1
    CEF_DOCKING_MODE_TOP_RIGHT = 2
    CEF_DOCKING_MODE_BOTTOM_LEFT = 3
    CEF_DOCKING_MODE_BOTTOM_RIGHT = 4
    CEF_DOCKING_MODE_CUSTOM = 5


#class cef_show_state_t(enum):
    CEF_SHOW_STATE_NORMAL = 1
    CEF_SHOW_STATE_MINIMIZED = 2
    CEF_SHOW_STATE_MAXIMIZED = 3
    CEF_SHOW_STATE_FULLSCREEN = 4


#class cef_touch_handle_state_flags_t(enum):
    CEF_THS_FLAG_NONE = 0
    CEF_THS_FLAG_ENABLED = 1
    CEF_THS_FLAG_ORIENTATION = 2
    CEF_THS_FLAG_ORIGIN = 4
    CEF_THS_FLAG_ALPHA = 8


#class cef_media_access_permission_types_t(enum):
    CEF_MEDIA_PERMISSION_NONE = 0
    CEF_MEDIA_PERMISSION_DEVICE_AUDIO_CAPTURE = 1
    CEF_MEDIA_PERMISSION_DEVICE_VIDEO_CAPTURE = 2
    CEF_MEDIA_PERMISSION_DESKTOP_AUDIO_CAPTURE = 4
    CEF_MEDIA_PERMISSION_DESKTOP_VIDEO_CAPTURE = 8


#class cef_permission_request_types_t(enum):
    CEF_PERMISSION_TYPE_NONE = 0
    CEF_PERMISSION_TYPE_ACCESSIBILITY_EVENTS = 1
    CEF_PERMISSION_TYPE_AR_SESSION = 2
    CEF_PERMISSION_TYPE_CAMERA_PAN_TILT_ZOOM = 4
    CEF_PERMISSION_TYPE_CAMERA_STREAM = 8
    CEF_PERMISSION_TYPE_CLIPBOARD = 16
    CEF_PERMISSION_TYPE_DISK_QUOTA = 32
    CEF_PERMISSION_TYPE_LOCAL_FONTS = 64
    CEF_PERMISSION_TYPE_GEOLOCATION = 128
    CEF_PERMISSION_TYPE_IDLE_DETECTION = 256
    CEF_PERMISSION_TYPE_MIC_STREAM = 512
    CEF_PERMISSION_TYPE_MIDI_SYSEX = 1024
    CEF_PERMISSION_TYPE_MULTIPLE_DOWNLOADS = 2048
    CEF_PERMISSION_TYPE_NOTIFICATIONS = 4096
    CEF_PERMISSION_TYPE_PROTECTED_MEDIA_IDENTIFIER = 8192
    CEF_PERMISSION_TYPE_REGISTER_PROTOCOL_HANDLER = 16384
    CEF_PERMISSION_TYPE_SECURITY_ATTESTATION = 32768
    CEF_PERMISSION_TYPE_STORAGE_ACCESS = 65536
    CEF_PERMISSION_TYPE_U2F_API_REQUEST = 131072
    CEF_PERMISSION_TYPE_VR_SESSION = 262144
    CEF_PERMISSION_TYPE_WINDOW_PLACEMENT = 524288


#class cef_permission_request_result_t(enum):
    CEF_PERMISSION_RESULT_ACCEPT = 1
    CEF_PERMISSION_RESULT_DENY = 2
    CEF_PERMISSION_RESULT_DISMISS = 3
    CEF_PERMISSION_RESULT_IGNORE = 4


#class cef_test_cert_type_t(enum):
    CEF_TEST_CERT_OK_IP = 1
    CEF_TEST_CERT_OK_DOMAIN = 2
    CEF_TEST_CERT_EXPIRED = 3
cef_log_severity_t = c_int
cef_state_t = c_int
cef_return_value_t = c_int
cef_cookie_priority_t = c_int
cef_cookie_same_site_t = c_int
cef_termination_status_t = c_int
cef_path_key_t = c_int
cef_storage_type_t = c_int
cef_errorcode_t = c_int
cef_cert_status_t = c_int
cef_window_open_disposition_t = c_int
cef_drag_operations_mask_t = c_int
cef_text_input_mode_t = c_int
cef_v8_accesscontrol_t = c_int
cef_v8_propertyattribute_t = c_int
cef_postdataelement_type_t = c_int
cef_resource_type_t = c_int
cef_transition_type_t = c_int
cef_urlrequest_flags_t = c_int
cef_urlrequest_status_t = c_int
cef_process_id_t = c_int
cef_thread_id_t = c_int
cef_thread_priority_t = c_int
cef_message_loop_type_t = c_int
cef_com_init_mode_t = c_int
cef_value_type_t = c_int
cef_jsdialog_type_t = c_int
cef_menu_id_t = c_int
cef_mouse_button_type_t = c_int
cef_touch_event_type_t = c_int
cef_pointer_type_t = c_int
cef_paint_element_type_t = c_int
cef_event_flags_t = c_int
cef_menu_item_type_t = c_int
cef_context_menu_type_flags_t = c_int
cef_context_menu_media_type_t = c_int
cef_context_menu_media_state_flags_t = c_int
cef_context_menu_edit_state_flags_t = c_int
cef_quick_menu_edit_state_flags_t = c_int
cef_key_event_type_t = c_int
cef_focus_source_t = c_int
cef_navigation_type_t = c_int
cef_xml_encoding_type_t = c_int
cef_xml_node_type_t = c_int
cef_dom_document_type_t = c_int
cef_dom_event_category_t = c_int
cef_dom_event_phase_t = c_int
cef_dom_node_type_t = c_int
cef_file_dialog_mode_t = c_int
cef_color_model_t = c_int
cef_duplex_mode_t = c_int
cef_cursor_type_t = c_int
cef_uri_unescape_rule_t = c_int
cef_json_parser_options_t = c_int
cef_json_writer_options_t = c_int
cef_pdf_print_margin_type_t = c_int
cef_scale_factor_t = c_int
cef_referrer_policy_t = c_int
cef_response_filter_status_t = c_int
cef_color_type_t = c_int
cef_alpha_type_t = c_int
cef_text_style_t = c_int
cef_main_axis_alignment_t = c_int
cef_cross_axis_alignment_t = c_int
cef_button_state_t = c_int
cef_horizontal_alignment_t = c_int
cef_menu_anchor_position_t = c_int
cef_menu_color_type_t = c_int
cef_ssl_version_t = c_int
cef_ssl_content_status_t = c_int
cef_scheme_options_t = c_int
cef_composition_underline_style_t = c_int
cef_channel_layout_t = c_int
cef_media_route_create_result_t = c_int
cef_media_route_connection_state_t = c_int
cef_media_sink_icon_type_t = c_int
cef_text_field_commands_t = c_int
cef_chrome_toolbar_type_t = c_int
cef_docking_mode_t = c_int
cef_show_state_t = c_int
cef_touch_handle_state_flags_t = c_int
cef_media_access_permission_types_t = c_int
cef_permission_request_types_t = c_int
cef_permission_request_result_t = c_int
cef_test_cert_type_t = c_int

class cef_point_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('x', c_int),
        ('y', c_int),
    )

class cef_rect_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('x', c_int),
        ('y', c_int),
        ('width', c_int),
        ('height', c_int),
    )

class cef_size_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('width', c_int),
        ('height', c_int),
    )

class cef_insets_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('top', c_int),
        ('left', c_int),
        ('bottom', c_int),
        ('right', c_int),
    )

class cef_basetime_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('val', int64),
    )

class cef_time_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('year', c_int),
        ('month', c_int),
        ('day_of_week', c_int),
        ('day_of_month', c_int),
        ('hour', c_int),
        ('minute', c_int),
        ('second', c_int),
        ('millisecond', c_int),
    )

class cef_settings_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('size', size_t),
        ('no_sandbox', c_int),
        ('browser_subprocess_path', cef_string_t),
        ('framework_dir_path', cef_string_t),
        ('main_bundle_path', cef_string_t),
        ('chrome_runtime', c_int),
        ('multi_threaded_message_loop', c_int),
        ('external_message_pump', c_int),
        ('windowless_rendering_enabled', c_int),
        ('command_line_args_disabled', c_int),
        ('cache_path', cef_string_t),
        ('root_cache_path', cef_string_t),
        ('user_data_path', cef_string_t),
        ('persist_session_cookies', c_int),
        ('persist_user_preferences', c_int),
        ('user_agent', cef_string_t),
        ('user_agent_product', cef_string_t),
        ('locale', cef_string_t),
        ('log_file', cef_string_t),
        ('log_severity', cef_log_severity_t),
        ('javascript_flags', cef_string_t),
        ('resources_dir_path', cef_string_t),
        ('locales_dir_path', cef_string_t),
        ('pack_loading_disabled', c_int),
        ('remote_debugging_port', c_int),
        ('uncaught_exception_stack_size', c_int),
        ('background_color', cef_color_t),
        ('accept_language_list', cef_string_t),
        ('cookieable_schemes_list', cef_string_t),
        ('cookieable_schemes_exclude_defaults', c_int),
    )

class cef_request_context_settings_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('size', size_t),
        ('cache_path', cef_string_t),
        ('persist_session_cookies', c_int),
        ('persist_user_preferences', c_int),
        ('accept_language_list', cef_string_t),
        ('cookieable_schemes_list', cef_string_t),
        ('cookieable_schemes_exclude_defaults', c_int),
    )

class cef_browser_settings_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('size', size_t),
        ('windowless_frame_rate', c_int),
        ('standard_font_family', cef_string_t),
        ('fixed_font_family', cef_string_t),
        ('serif_font_family', cef_string_t),
        ('sans_serif_font_family', cef_string_t),
        ('cursive_font_family', cef_string_t),
        ('fantasy_font_family', cef_string_t),
        ('default_font_size', c_int),
        ('default_fixed_font_size', c_int),
        ('minimum_font_size', c_int),
        ('minimum_logical_font_size', c_int),
        ('default_encoding', cef_string_t),
        ('remote_fonts', cef_state_t),
        ('javascript', cef_state_t),
        ('javascript_close_windows', cef_state_t),
        ('javascript_access_clipboard', cef_state_t),
        ('javascript_dom_paste', cef_state_t),
        ('image_loading', cef_state_t),
        ('image_shrink_standalone_to_fit', cef_state_t),
        ('text_area_resize', cef_state_t),
        ('tab_to_links', cef_state_t),
        ('local_storage', cef_state_t),
        ('databases', cef_state_t),
        ('webgl', cef_state_t),
        ('background_color', cef_color_t),
        ('accept_language_list', cef_string_t),
        ('chrome_status_bubble', cef_state_t),
    )

class cef_urlparts_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('spec', cef_string_t),
        ('scheme', cef_string_t),
        ('username', cef_string_t),
        ('password', cef_string_t),
        ('host', cef_string_t),
        ('port', cef_string_t),
        ('origin', cef_string_t),
        ('path', cef_string_t),
        ('query', cef_string_t),
        ('fragment', cef_string_t),
    )

class cef_cookie_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('name', cef_string_t),
        ('value', cef_string_t),
        ('domain', cef_string_t),
        ('path', cef_string_t),
        ('secure', c_int),
        ('httponly', c_int),
        ('creation', cef_basetime_t),
        ('last_access', cef_basetime_t),
        ('has_expires', c_int),
        ('expires', cef_basetime_t),
        ('same_site', cef_cookie_same_site_t),
        ('priority', cef_cookie_priority_t),
    )

class cef_draggable_region_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('bounds', cef_rect_t),
        ('draggable', c_int),
    )

class cef_screen_info_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('device_scale_factor', float),
        ('depth', c_int),
        ('depth_per_component', c_int),
        ('is_monochrome', c_int),
        ('rect', cef_rect_t),
        ('available_rect', cef_rect_t),
    )

class cef_mouse_event_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('x', c_int),
        ('y', c_int),
        ('modifiers', uint32),
    )

class cef_touch_event_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('id', c_int),
        ('x', float),
        ('y', float),
        ('radius_x', float),
        ('radius_y', float),
        ('rotation_angle', float),
        ('pressure', float),
        ('type', cef_touch_event_type_t),
        ('modifiers', uint32),
        ('pointer_type', cef_pointer_type_t),
    )

class cef_key_event_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('type', cef_key_event_type_t),
        ('modifiers', uint32),
        ('windows_key_code', c_int),
        ('native_key_code', c_int),
        ('is_system_key', c_int),
        ('character', char16),
        ('unmodified_character', char16),
        ('focus_on_editable_field', c_int),
    )

class cef_popup_features_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('x', c_int),
        ('xSet', c_int),
        ('y', c_int),
        ('ySet', c_int),
        ('width', c_int),
        ('widthSet', c_int),
        ('height', c_int),
        ('heightSet', c_int),
        ('menuBarVisible', c_int),
        ('statusBarVisible', c_int),
        ('toolBarVisible', c_int),
        ('scrollbarsVisible', c_int),
    )

class cef_cursor_info_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('hotspot', cef_point_t),
        ('image_scale_factor', float),
        ('buffer', POINTER(c_void)),
        ('size', cef_size_t),
    )

class cef_pdf_print_settings_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('header_footer_title', cef_string_t),
        ('header_footer_url', cef_string_t),
        ('page_width', c_int),
        ('page_height', c_int),
        ('scale_factor', c_int),
        ('margin_top', c_int),
        ('margin_right', c_int),
        ('margin_bottom', c_int),
        ('margin_left', c_int),
        ('margin_type', cef_pdf_print_margin_type_t),
        ('header_footer_enabled', c_int),
        ('selection_only', c_int),
        ('landscape', c_int),
        ('backgrounds_enabled', c_int),
    )

class cef_box_layout_settings_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('horizontal', c_int),
        ('inside_border_horizontal_spacing', c_int),
        ('inside_border_vertical_spacing', c_int),
        ('inside_border_insets', cef_insets_t),
        ('between_child_spacing', c_int),
        ('main_axis_alignment', cef_main_axis_alignment_t),
        ('cross_axis_alignment', cef_cross_axis_alignment_t),
        ('minimum_cross_axis_size', c_int),
        ('default_flex', c_int),
    )

class cef_range_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('xfrom', c_int),
        ('to', c_int),
    )

class cef_composition_underline_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('range', cef_range_t),
        ('color', cef_color_t),
        ('background_color', cef_color_t),
        ('thick', c_int),
        ('style', cef_composition_underline_style_t),
    )

class cef_audio_parameters_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('channel_layout', cef_channel_layout_t),
        ('sample_rate', c_int),
        ('frames_per_buffer', c_int),
    )

class cef_media_sink_device_info_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('ip_address', cef_string_t),
        ('port', c_int),
        ('model_name', cef_string_t),
    )

class cef_touch_handle_state_t(Structure):
    _align_ = CEFALIGN
    _fields_ = (
        ('touch_handle_id', c_int),
        ('flags', uint32),
        ('enabled', c_int),
        ('orientation', cef_horizontal_alignment_t),
        ('mirror_vertical', c_int),
        ('mirror_horizontal', c_int),
        ('origin', cef_point_t),
        ('alpha', float),
    )

if linux:

    class cef_main_args_t(Structure):
        _align_ = CEFALIGN
        _fields_ = (
            ('argc', c_int),
            ('argv', POINTER(POINTER(char))),
        )

if linux:

    class cef_window_info_t(Structure):
        _align_ = CEFALIGN
        _fields_ = (
            ('window_name', cef_string_t),
            ('bounds', cef_rect_t),
            ('parent_window', cef_window_handle_t),
            ('windowless_rendering_enabled', c_int),
            ('shared_texture_enabled', c_int),
            ('external_begin_frame_enabled', c_int),
            ('window', cef_window_handle_t),
        )

#int cef_get_min_log_level(void);
@CEFENTRY(c_int, "cef_get_min_log_level")
def cef_get_min_log_level():
    return cef_get_min_log_level._api_()

#int cef_get_vlog_level(char* file_start, size_t N);
@CEFENTRY(c_int, "cef_get_vlog_level", POINTER(char), size_t)
def cef_get_vlog_level(file_start, N):
    return cef_get_vlog_level._api_(file_start, N)

#void cef_log(char* file, int line, int severity, char* message);
@CEFENTRY(c_void, "cef_log", POINTER(char), c_int, c_int, POINTER(char))
def cef_log(file, line, severity, message):
    return cef_log._api_(file, line, severity, message)

#cef_platform_thread_id_t cef_get_current_platform_thread_id(void);
@CEFENTRY(cef_platform_thread_id_t, "cef_get_current_platform_thread_id")
def cef_get_current_platform_thread_id():
    return cef_get_current_platform_thread_id._api_()

#cef_platform_thread_handle_t cef_get_current_platform_thread_handle(void);
@CEFENTRY(cef_platform_thread_handle_t, "cef_get_current_platform_thread_handle")
def cef_get_current_platform_thread_handle():
    return cef_get_current_platform_thread_handle._api_()

#int cef_time_to_timet(cef_time_t* cef_time, time_t* time);
@CEFENTRY(c_int, "cef_time_to_timet", POINTER(cef_time_t), POINTER(time_t))
def cef_time_to_timet(cef_time, time):
    return cef_time_to_timet._api_(cef_time, time)

#int cef_time_from_timet(time_t time, cef_time_t* cef_time);
@CEFENTRY(c_int, "cef_time_from_timet", time_t, POINTER(cef_time_t))
def cef_time_from_timet(time, cef_time):
    return cef_time_from_timet._api_(time, cef_time)

#int cef_time_to_doublet(cef_time_t* cef_time, double* time);
@CEFENTRY(c_int, "cef_time_to_doublet", POINTER(cef_time_t), POINTER(double))
def cef_time_to_doublet(cef_time, time):
    return cef_time_to_doublet._api_(cef_time, time)

#int cef_time_from_doublet(double time, cef_time_t* cef_time);
@CEFENTRY(c_int, "cef_time_from_doublet", double, POINTER(cef_time_t))
def cef_time_from_doublet(time, cef_time):
    return cef_time_from_doublet._api_(time, cef_time)

#int cef_time_now(cef_time_t* cef_time);
@CEFENTRY(c_int, "cef_time_now", POINTER(cef_time_t))
def cef_time_now(cef_time):
    return cef_time_now._api_(cef_time)

#int cef_time_delta(cef_time_t* cef_time1, cef_time_t* cef_time2, long long* delta);
@CEFENTRY(c_int, "cef_time_delta", POINTER(cef_time_t), POINTER(cef_time_t), POINTER(longlong))
def cef_time_delta(cef_time1, cef_time2, delta):
    return cef_time_delta._api_(cef_time1, cef_time2, delta)

#void cef_trace_event_instant(char* category, char* name, char* arg1_name, uint64 arg1_val, char* arg2_name, uint64 arg2_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_instant", POINTER(char), POINTER(char), POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_event_instant(category, name, arg1_name, arg1_val, arg2_name, arg2_val, copy):
    return cef_trace_event_instant._api_(category, name, arg1_name, arg1_val, arg2_name, arg2_val, copy)

#void cef_trace_event_begin(char* category, char* name, char* arg1_name, uint64 arg1_val, char* arg2_name, uint64 arg2_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_begin", POINTER(char), POINTER(char), POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_event_begin(category, name, arg1_name, arg1_val, arg2_name, arg2_val, copy):
    return cef_trace_event_begin._api_(category, name, arg1_name, arg1_val, arg2_name, arg2_val, copy)

#void cef_trace_event_end(char* category, char* name, char* arg1_name, uint64 arg1_val, char* arg2_name, uint64 arg2_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_end", POINTER(char), POINTER(char), POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_event_end(category, name, arg1_name, arg1_val, arg2_name, arg2_val, copy):
    return cef_trace_event_end._api_(category, name, arg1_name, arg1_val, arg2_name, arg2_val, copy)

#void cef_trace_counter(char* category, char* name, char* value1_name, uint64 value1_val, char* value2_name, uint64 value2_val, int copy);
@CEFENTRY(c_void, "cef_trace_counter", POINTER(char), POINTER(char), POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_counter(category, name, value1_name, value1_val, value2_name, value2_val, copy):
    return cef_trace_counter._api_(category, name, value1_name, value1_val, value2_name, value2_val, copy)

#void cef_trace_counter_id(char* category, char* name, uint64 id, char* value1_name, uint64 value1_val, char* value2_name, uint64 value2_val, int copy);
@CEFENTRY(c_void, "cef_trace_counter_id", POINTER(char), POINTER(char), uint64, POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_counter_id(category, name, id, value1_name, value1_val, value2_name, value2_val, copy):
    return cef_trace_counter_id._api_(category, name, id, value1_name, value1_val, value2_name, value2_val, copy)

#void cef_trace_event_async_begin(char* category, char* name, uint64 id, char* arg1_name, uint64 arg1_val, char* arg2_name, uint64 arg2_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_async_begin", POINTER(char), POINTER(char), uint64, POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_event_async_begin(category, name, id, arg1_name, arg1_val, arg2_name, arg2_val, copy):
    return cef_trace_event_async_begin._api_(category, name, id, arg1_name, arg1_val, arg2_name, arg2_val, copy)

#void cef_trace_event_async_step_into(char* category, char* name, uint64 id, uint64 step, char* arg1_name, uint64 arg1_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_async_step_into", POINTER(char), POINTER(char), uint64, uint64, POINTER(char), uint64, c_int)
def cef_trace_event_async_step_into(category, name, id, step, arg1_name, arg1_val, copy):
    return cef_trace_event_async_step_into._api_(category, name, id, step, arg1_name, arg1_val, copy)

#void cef_trace_event_async_step_past(char* category, char* name, uint64 id, uint64 step, char* arg1_name, uint64 arg1_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_async_step_past", POINTER(char), POINTER(char), uint64, uint64, POINTER(char), uint64, c_int)
def cef_trace_event_async_step_past(category, name, id, step, arg1_name, arg1_val, copy):
    return cef_trace_event_async_step_past._api_(category, name, id, step, arg1_name, arg1_val, copy)

#void cef_trace_event_async_end(char* category, char* name, uint64 id, char* arg1_name, uint64 arg1_val, char* arg2_name, uint64 arg2_val, int copy);
@CEFENTRY(c_void, "cef_trace_event_async_end", POINTER(char), POINTER(char), uint64, POINTER(char), uint64, POINTER(char), uint64, c_int)
def cef_trace_event_async_end(category, name, id, arg1_name, arg1_val, arg2_name, arg2_val, copy):
    return cef_trace_event_async_end._api_(category, name, id, arg1_name, arg1_val, arg2_name, arg2_val, copy)

if linux:
    #XDisplay* cef_get_xdisplay(void);
    @CEFENTRY(POINTER(XDisplay), "cef_get_xdisplay")
    def cef_get_xdisplay():
        return cef_get_xdisplay._api_()

#char* cef_api_hash(int entry);
@CEFENTRY(POINTER(char), "cef_api_hash", c_int)
def cef_api_hash(entry):
    return cef_api_hash._api_(entry)

#int cef_version_info(int entry);
@CEFENTRY(c_int, "cef_version_info", c_int)
def cef_version_info(entry):
    return cef_version_info._api_(entry)
